### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by GarciaLnk** [FL33TW00D/laserbeak#21]
The demo site throws an error whenever I try to translate/summarize a text selection.

I tried it on Chrome 113.0 and 114.0 under Windows.

Here's the error trace:

```
794-4ba36314828f3c2e.js:1 panicked at 'called `Option::unwrap()` on a `None` value', /Users/fleetwood/Code/rumble/rumble/src/transformers/generation/generate.rs:138:53

Stack:

Error
    at t.wbg.__wbg_new_abda76e883ba8a5f (https://summize.fleetwood.dev/_next/static/chunks/794-4ba36314828f3c2e.js:1:5028)
    at https://summize.fleetwood.dev/_next/static/media/rumble_bg.0f8c1e45.wasm:wasm-function[2299]:0x34e0b0
    at https://summize.fleetwood.dev/_next/static/media/rumble_bg.0f8c1e45.wasm:wasm-function[2983]:0x364c25
    at https://summize.fleetwood.dev/_next/static/media/rumble_bg.0f8c1e45.wasm:wasm-function[2816]:0x360408
    at https://summize.fleetwood.dev/_next/static/media/rumble_bg.0f8c1e45.wasm:wasm-function[219]:0xa253d
    at https://summize.fleetwood.dev/_next/static/media/rumble_bg.0f8c1e45.wasm:wasm-function[201]:0x62b15
    at https://summize.fleetwood.dev/_next/static/media/rumble_bg.0f8c1e45.wasm:wasm-function[1271]:0x2e1de5
    at https://summize.fleetwood.dev/_next/static/media/rumble_bg.0f8c1e45.wasm:wasm-function[3163]:0x3686e2
    at m (https://summize.fleetwood.dev/_next/static/chunks/794-4ba36314828f3c2e.js:1:1478)
    at _ (https://summize.fleetwood.dev/_next/static/chunks/794-4ba36314828f3c2e.js:1:1354)


t.wbg.__wbg_error_f851667af71bcfc6 @ 794-4ba36314828f3c2e.js:1
$func2299 @ rumble_bg.0f8c1e45.wasm:0x34e17c
$func2983 @ rumble_bg.0f8c1e45.wasm:0x364c25
$func2816 @ rumble_bg.0f8c1e45.wasm:0x360408
$func219 @ rumble_bg.0f8c1e45.wasm:0xa253d
$func201 @ rumble_bg.0f8c1e45.wasm:0x62b15
$func1271 @ rumble_bg.0f8c1e45.wasm:0x2e1de5
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h75150ce7cfed22a0 @ rumble_bg.0f8c1e45.wasm:0x3686e2
m @ 794-4ba36314828f3c2e.js:1
_ @ 794-4ba36314828f3c2e.js:1
Promise.then (async)
t.wbg.__wbg_then_ec5db6d509eb475f @ 794-4ba36314828f3c2e.js:2
$func1876 @ rumble_bg.0f8c1e45.wasm:0x332ed8
$func2287 @ rumble_bg.0f8c1e45.wasm:0x34d4e7
$func1286 @ rumble_bg.0f8c1e45.wasm:0x2e4800
$func408 @ rumble_bg.0f8c1e45.wasm:0x1a3e51
$func1775 @ rumble_bg.0f8c1e45.wasm:0x32aee5
$func1807 @ rumble_bg.0f8c1e45.wasm:0x32d74b
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h75150ce7cfed22a0 @ rumble_bg.0f8c1e45.wasm:0x3686e2
m @ 794-4ba36314828f3c2e.js:1
_ @ 794-4ba36314828f3c2e.js:1
Promise.then (async)
t.wbg.__wbg_then_f753623316e2873a @ 794-4ba36314828f3c2e.js:2
$func1439 @ rumble_bg.0f8c1e45.wasm:0x2f7b60
$func228 @ rumble_bg.0f8c1e45.wasm:0xc4a41
$func240 @ rumble_bg.0f8c1e45.wasm:0xdc380
$func201 @ rumble_bg.0f8c1e45.wasm:0x62a34
$func1271 @ rumble_bg.0f8c1e45.wasm:0x2e1de5
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h75150ce7cfed22a0 @ rumble_bg.0f8c1e45.wasm:0x3686e2
m @ 794-4ba36314828f3c2e.js:1
_ @ 794-4ba36314828f3c2e.js:1
Promise.then (async)
t.wbg.__wbg_then_ec5db6d509eb475f @ 794-4ba36314828f3c2e.js:2
$func1695 @ rumble_bg.0f8c1e45.wasm:0x322022
$func2315 @ rumble_bg.0f8c1e45.wasm:0x34ee51
$wasm_bindgen__convert__closures__invoke2_mut__h33a68d4fde6fd468 @ rumble_bg.0f8c1e45.wasm:0x3684cc
B @ 794-4ba36314828f3c2e.js:1
r @ 794-4ba36314828f3c2e.js:2
t.wbg.__wbg_new_9d3a9ce4282a18a8 @ 794-4ba36314828f3c2e.js:2
$session_stream @ rumble_bg.0f8c1e45.wasm:0x359daf
stream @ 794-4ba36314828f3c2e.js:1
(anonymous) @ 333.3da92a97809f6ece.js:1
(anonymous) @ 333.3da92a97809f6ece.js:1
a @ 333.3da92a97809f6ece.js:1
run @ 333.3da92a97809f6ece.js:1
n @ 333.3da92a97809f6ece.js:1

rumble_bg.0f8c1e45.wasm:0x34e1dd Uncaught (in promise) RuntimeError: unreachable
    at rumble_bg.0f8c1e45.wasm:0x34e1dd
    at rumble_bg.0f8c1e45.wasm:0x364c25
    at rumble_bg.0f8c1e45.wasm:0x360408
    at rumble_bg.0f8c1e45.wasm:0xa253d
    at rumble_bg.0f8c1e45.wasm:0x62b15
    at rumble_bg.0f8c1e45.wasm:0x2e1de5
    at rumble_bg.0f8c1e45.wasm:0x3686e2
    at m (794-4ba36314828f3c2e.js:1:1478)
    at _ (794-4ba36314828f3c2e.js:1:1354)
```

**Comment by FL33TW00D** [comment]
Hey @GarciaLnk,
Appreciate you trying it out!

Currently, there is no validation to check if all the files have been downloaded successfully.

Try erasing your IndexedDB with `window.indexedDB.deleteDatabase("models")`, it should try and fetch the models again.

**Comment by GarciaLnk** [comment]
I tried a couple more times after erasing the IndexedDB and I keep getting the same error.

**Comment by FL33TW00D** [comment]
@GarciaLnk can you paste the console output? Or we can discuss on discord: Fleetwood#1949
